### ISSUE TITLE
[유미] 2022.07.25 TODO

### ISSUE THREAD

**Issue by ymStudyLog** [Wanted-Pre-Onboarding-FE-Team5/snplab-admin#15]
### TODO
1. [x]  api (get,post,patch) 생성
2. [x]  layout - Globalstyles에 선언한 컬러변수로 치환
3. [x]  Search 컴포넌트 기능 구현

**Comment by ymStudyLog** [comment]
done
