### ISSUE TITLE
[연진] 2022.07.21 TODO

### ISSUE THREAD

**Issue by yeonjinkimm** [Wanted-Pre-Onboarding-FE-Team5/snplab-admin#2]
### TODO
- [x]  Recoil 공부
- [x] Modal : createPortal 구현
  - [x]  Modal Layout : 거주지 선택 모달 (Region.tsx)
  - [x]  Modal Layout : 지원 완료 확인 모달 (Confirm.tsx)
  - [x] Form.tsx에 거주지 선택 모달 (Region.tsx) 연결
  - [x] Form.tsx에 지원 완료 확인 모달 (Confirm.tsx) 연결
