### ISSUE TITLE
[유미] 2022.07.26 TODO

### ISSUE THREAD

**Issue by ymStudyLog** [Wanted-Pre-Onboarding-FE-Team5/snplab-admin#24]
### TODO
1. [x]  PrivacyPolicy 폼 -> 개인정보 페이지 이동시 스크롤 맨위로
2. [x]  Search -> 드롭다운 이외의 부분 클릭시 닫히게, SearchInput useRef로 최적화, 최종 쿼리만 아톰 저장할 수 있게?
3. [x] aip -> typescript 처리

**Comment by ymStudyLog** [comment]
done
